# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Test for AQT configs."""
import itertools
from absl.testing import absltest
from absl.testing import parameterized
from aqt.jax.v2 import config
from aqt.jax.v2 import utils
import jax.numpy as jnp


class AqtConfigTest(parameterized.TestCase):

  def test_config_v4(self):
    cfg = config.config_v4(
        fwd_bits=8,
        dlhs_bits=7,
        drhs_bits=6,
        rng_type='custom-1',
        dlhs_local_aqt=config.LocalAqt(2),
        drhs_local_aqt=config.LocalAqt(3),
        fwd_accumulator_dtype=jnp.int16,
        dlhs_accumulator_dtype=jnp.int8,
        drhs_accumulator_dtype=jnp.int4,
    )
    expected_cfg_str = """DotGeneral(fwd=DotGeneralRaw(lhs=Tensor(quantizer=Quantizer(numerics=IntNumerics(bits=8,
                                                                                 preserve_zero=True,
                                                                                 preserve_max_val=False,
                                                                                 clip=True,
                                                                                 clip_gradient=False,
                                                                                 round=True,
                                                                                 noise_fn=None,
                                                                                 dtype=<class 'jax.numpy.int8'>),
                                                            calib_shared_axes=None,
                                                            scale_stop_grad=True,
                                                            calibration=AbsMaxCalibration(),
                                                            po2_scale=False,
                                                            context=Context(key=None,
                                                                            train_step=None)),
                                        use_fwd_quant=None,
                                        dequant_mode=<DequantMode.OUTPUT: 1>),
                             rhs=Tensor(quantizer=Quantizer(numerics=IntNumerics(bits=8,
                                                                                 preserve_zero=True,
                                                                                 preserve_max_val=False,
                                                                                 clip=True,
                                                                                 clip_gradient=False,
                                                                                 round=True,
                                                                                 noise_fn=None,
                                                                                 dtype=<class 'jax.numpy.int8'>),
                                                            calib_shared_axes=None,
                                                            scale_stop_grad=True,
                                                            calibration=AbsMaxCalibration(),
                                                            po2_scale=False,
                                                            context=Context(key=None,
                                                                            train_step=None)),
                                        use_fwd_quant=None,
                                        dequant_mode=<DequantMode.OUTPUT: 1>),
                             dg_accumulator_dtype=<class 'jax.numpy.int16'>,
                             local_aqt=None,
                             jax_scope_name='aqt_fwd'),
           dlhs=DotGeneralRaw(lhs=Tensor(quantizer=Quantizer(numerics=IntNumerics(bits=7,
                                                                                  preserve_zero=True,
                                                                                  preserve_max_val=False,
                                                                                  clip=True,
                                                                                  clip_gradient=False,
                                                                                  round=True,
                                                                                  noise_fn=RandomCenteredUniform(),
                                                                                  dtype=<class 'jax.numpy.int8'>),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=None,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              rhs=Tensor(quantizer=Quantizer(numerics=IntNumerics(bits=7,
                                                                                  preserve_zero=True,
                                                                                  preserve_max_val=False,
                                                                                  clip=True,
                                                                                  clip_gradient=False,
                                                                                  round=True,
                                                                                  noise_fn=None,
                                                                                  dtype=<class 'jax.numpy.int8'>),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=False,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              dg_accumulator_dtype=<class 'jax.numpy.int8'>,
                              local_aqt=LocalAqt(contraction_axis_shard_count=2),
                              jax_scope_name='aqt_dlhs'),
           drhs=DotGeneralRaw(lhs=Tensor(quantizer=Quantizer(numerics=IntNumerics(bits=6,
                                                                                  preserve_zero=True,
                                                                                  preserve_max_val=False,
                                                                                  clip=True,
                                                                                  clip_gradient=False,
                                                                                  round=True,
                                                                                  noise_fn=RandomCenteredUniform(),
                                                                                  dtype=<class 'jax.numpy.int8'>),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=None,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              rhs=Tensor(quantizer=Quantizer(numerics=IntNumerics(bits=6,
                                                                                  preserve_zero=True,
                                                                                  preserve_max_val=False,
                                                                                  clip=True,
                                                                                  clip_gradient=False,
                                                                                  round=True,
                                                                                  noise_fn=None,
                                                                                  dtype=<class 'jax.numpy.int8'>),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=False,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              dg_accumulator_dtype=<class 'jax.numpy.int4'>,
                              local_aqt=LocalAqt(contraction_axis_shard_count=3),
                              jax_scope_name='aqt_drhs'))"""
    utils.test_pprint_eq(cfg, expected_cfg_str)

  def test_configv4_original(self):
    expected_cfg_str = """DotGeneral(fwd=DotGeneralRaw(lhs=Tensor(quantizer=Quantizer(numerics=IntNumerics(bits=8,
                                                                                 preserve_zero=True,
                                                                                 preserve_max_val=False,
                                                                                 clip=True,
                                                                                 clip_gradient=False,
                                                                                 round=True,
                                                                                 noise_fn=None,
                                                                                 dtype=<class 'jax.numpy.int8'>),
                                                            calib_shared_axes=None,
                                                            scale_stop_grad=True,
                                                            calibration=AbsMaxCalibration(),
                                                            po2_scale=False,
                                                            context=Context(key=None,
                                                                            train_step=None)),
                                        use_fwd_quant=None,
                                        dequant_mode=<DequantMode.OUTPUT: 1>),
                             rhs=Tensor(quantizer=Quantizer(numerics=IntNumerics(bits=8,
                                                                                 preserve_zero=True,
                                                                                 preserve_max_val=False,
                                                                                 clip=True,
                                                                                 clip_gradient=False,
                                                                                 round=True,
                                                                                 noise_fn=None,
                                                                                 dtype=<class 'jax.numpy.int8'>),
                                                            calib_shared_axes=None,
                                                            scale_stop_grad=True,
                                                            calibration=AbsMaxCalibration(),
                                                            po2_scale=False,
                                                            context=Context(key=None,
                                                                            train_step=None)),
                                        use_fwd_quant=None,
                                        dequant_mode=<DequantMode.OUTPUT: 1>),
                             dg_accumulator_dtype=<class 'jax.numpy.int32'>,
                             local_aqt=None,
                             jax_scope_name='aqt_fwd'),
           dlhs=DotGeneralRaw(lhs=Tensor(quantizer=Quantizer(numerics=IntNumerics(bits=8,
                                                                                  preserve_zero=True,
                                                                                  preserve_max_val=False,
                                                                                  clip=True,
                                                                                  clip_gradient=False,
                                                                                  round=True,
                                                                                  noise_fn=JaxUniform(),
                                                                                  dtype=<class 'jax.numpy.int8'>),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=None,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              rhs=Tensor(quantizer=Quantizer(numerics=IntNumerics(bits=8,
                                                                                  preserve_zero=True,
                                                                                  preserve_max_val=False,
                                                                                  clip=True,
                                                                                  clip_gradient=False,
                                                                                  round=True,
                                                                                  noise_fn=None,
                                                                                  dtype=<class 'jax.numpy.int8'>),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=False,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              dg_accumulator_dtype=<class 'jax.numpy.int32'>,
                              local_aqt=None,
                              jax_scope_name='aqt_dlhs'),
           drhs=DotGeneralRaw(lhs=Tensor(quantizer=Quantizer(numerics=NoNumerics(noise_fn=JaxUniform(),
                                                                                 dtype=None),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=None,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              rhs=Tensor(quantizer=Quantizer(numerics=NoNumerics(noise_fn=None,
                                                                                 dtype=None),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=False,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              dg_accumulator_dtype=None,
                              local_aqt=None,
                              jax_scope_name='aqt_drhs'))"""
    utils.test_pprint_eq(config.config_v4(), expected_cfg_str)

  def test_config_fwd_fp8(self):
    expected_cfg = """DotGeneral(fwd=DotGeneralRaw(lhs=Tensor(quantizer=Quantizer(numerics=Fp8Numerics(dtype=<class 'jax.numpy.float8_e4m3fn'>,
                                                                                 exponent_bits=4,
                                                                                 mantissa_bits=3,
                                                                                 noise_fn=None),
                                                            calib_shared_axes=None,
                                                            scale_stop_grad=True,
                                                            calibration=AbsMaxCalibration(),
                                                            po2_scale=False,
                                                            context=Context(key=None,
                                                                            train_step=None)),
                                        use_fwd_quant=None,
                                        dequant_mode=<DequantMode.OUTPUT: 1>),
                             rhs=Tensor(quantizer=Quantizer(numerics=Fp8Numerics(dtype=<class 'jax.numpy.float8_e4m3fn'>,
                                                                                 exponent_bits=4,
                                                                                 mantissa_bits=3,
                                                                                 noise_fn=None),
                                                            calib_shared_axes=None,
                                                            scale_stop_grad=True,
                                                            calibration=AbsMaxCalibration(),
                                                            po2_scale=False,
                                                            context=Context(key=None,
                                                                            train_step=None)),
                                        use_fwd_quant=None,
                                        dequant_mode=<DequantMode.OUTPUT: 1>),
                             dg_accumulator_dtype=<class 'jax.numpy.float32'>,
                             local_aqt=None,
                             jax_scope_name='aqt_fwd'),
           dlhs=DotGeneralRaw(lhs=Tensor(quantizer=Quantizer(numerics=NoNumerics(noise_fn=None,
                                                                                 dtype=None),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=None,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              rhs=Tensor(quantizer=Quantizer(numerics=NoNumerics(noise_fn=None,
                                                                                 dtype=None),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=False,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              dg_accumulator_dtype=None,
                              local_aqt=None,
                              jax_scope_name='aqt_dlhs'),
           drhs=DotGeneralRaw(lhs=Tensor(quantizer=Quantizer(numerics=NoNumerics(noise_fn=None,
                                                                                 dtype=None),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=None,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              rhs=Tensor(quantizer=Quantizer(numerics=NoNumerics(noise_fn=None,
                                                                                 dtype=None),
                                                             calib_shared_axes=None,
                                                             scale_stop_grad=True,
                                                             calibration=AbsMaxCalibration(),
                                                             po2_scale=False,
                                                             context=Context(key=None,
                                                                             train_step=None)),
                                         use_fwd_quant=False,
                                         dequant_mode=<DequantMode.OUTPUT: 1>),
                              dg_accumulator_dtype=None,
                              local_aqt=None,
                              jax_scope_name='aqt_drhs'))"""
    utils.test_pprint_eq(config.config_fwd_fp8(), expected_cfg)

  @parameterized.parameters([
      dict(
          fwd_bits=fwd_bits,
          dlhs_bits=dlhs_bits,
          drhs_bits=drhs_bits,
          rng_type=rng_type,
          dlhs_local_aqt=dlhs_local_aqt,
          drhs_local_aqt=drhs_local_aqt,
          fwd_accumulator_dtype=fwd_accumulator_dtype,
          dlhs_accumulator_dtype=dlhs_accumulator_dtype,
          drhs_accumulator_dtype=drhs_accumulator_dtype,
      )
      for fwd_bits, dlhs_bits, drhs_bits, rng_type, dlhs_local_aqt, drhs_local_aqt, fwd_accumulator_dtype, dlhs_accumulator_dtype, drhs_accumulator_dtype in itertools.product(
          [8, 4, 2, None],
          [8, 4, 2, None],
          [8, 4, 2, None],
          ['jax.uniform', 'custom-1'],
          [config.LocalAqt(3), None],
          [config.LocalAqt(2), None],
          [jnp.float32, jnp.bfloat16, jnp.int8, jnp.int32, None],
          [jnp.float32, jnp.bfloat16, jnp.int8, jnp.int32, None],
          [jnp.float32, jnp.bfloat16, jnp.int8, jnp.int32, None],
      )
  ])
  def test_config_v4_new(self, **kwargs):
    utils.test_pprint_eq(
        config.config_v4(**kwargs), config.config_v4_old(**kwargs)
    )


if __name__ == '__main__':
  absltest.main()
